- build.sbt
- src/main/scala/io/gatling/build/BaseSettingsPlugin.scala
Motivation:
We want to be able to compile with more modern Java version and still be compatible with Java 8, as long as source code is compatible.
In particular, we don't want to crash with NoSuchMethodError because we would be linking to the new ByteBuffer/Buffer overloads introduced in Java 8.
Modifications:
* enable `-release` scalac option when building this plugin
* enable `-release` scalac option for projects importing this plugin
Result:
This plugin can now compile projects with Java 11 and still emit bytecode compatible with Java 8.
> Enforce Java 8 API

- src/main/resources/default.scalafix.conf
Motivation:
gatling uses classes in xsbt and xsbti packages.
Modifications:
Change last import group rule to include additional xsbt and xsbti packages
Result:
gatling will be able to use xsbt and xsbti shadowing
Possible impact:
This sort a hypothetical sbti package altogether with the wanted ones.
> Add xsbt and xsbti on same import group as sbt

- src/main/scala/io/gatling/build/GatlingOssPlugin.scala
Motivation:
Avoid to configure the same thing everywhere
Modifications:
Default value "io.gatling" for sonatypeProfileName settings
Result:
No nee to override sonatypeProfileName when groupId is somehting else than "io.gatling"
> Add default sonatype profile name

- build.sbt
- src/main/scala/io/gatling/build/automated/GatlingAutomatedScalafixPlugin.scala
- src/main/scala/io/gatling/build/automated/GatlingAutomatedScalafmtPlugin.scala
- src/sbt-test/gatling-build-plugin/loadPlugin/project/build.properties
- src/sbt-test/gatling-build-plugin/scalaVersion/project/build.properties
- src/sbt-test/scalafix/automated/project/build.properties
- src/sbt-test/scalafix/automated/test
- src/sbt-test/scalafix/none/project/build.properties
- src/sbt-test/scalafix/none/test
- src/sbt-test/scalafmt/automated/project/build.properties
- src/sbt-test/scalafmt/automated/test
- src/sbt-test/scalafmt/none/project/build.properties
- src/sbt-test/scalafmt/none/test
**Motivation:**
CI must deactivate on compile scalafix and scalafmt parsing
**Modification:**
GatlingAutomatedScalafixPlugin scalafix on compile respect scalafixOnCompile setting
> Deactivate scalafix and scalafmt on compile on CI, closes OPS-74

- .github/workflows/create_release.yml
- src/main/scala/io/gatling/build/versioning/GatlingVersioningPlugin.scala
Motivation:
Create release workflow didn't work.
Modifications:
* As sbt does not play nice with stdout, write the version to a file
* Use a PAT (Personal Access Token) to trigger another workflow with the tag push
* Remove useless job output (as GitHub does not display it as expected)
Result:
One can manually launch this create_release workflow to create a well formed tag.
> Fix create release workflow

- .github/workflows/build.yml
- src/main/scala/io/gatling/build/versioning/GatlingBump.scala
Motivation:
First 4.0.0 tag was published as 4.0.0-dirty-SNAPSHOT as a file were modified
during test (a step before publish).
Modifications:
Add a check for correct header during the build
Result:
No more modification during a release for headers
> Check headers in build workflow

- src/main/scala/io/gatling/build/GatlingOssPlugin.scala
- src/test/scala/io/gatling/build/GatlingOssPluginSpec.scala
Motivation:
Several bad versions appears in maven central.
Modifications:
Instead of deny milestone, only allow version X.Y.Z to be published to maven central.
Result:
No more bad version on maven central.
> Ensure version is stable before publishing to Sonatype

- src/main/scala/io/gatling/build/release/GatlingReleasePlugin.scala
Motivation:
As sbt does not play nice with standard output, we prefer to rely on file.
Modifications:
Add an extra step during release: writeCurrentVersion
Result:
The version is written on target/release-info just before releasing.
> Write current version in target/release-info

- src/main/scala/io/gatling/build/GatlingOssPlugin.scala
- src/test/scala/io/gatling/build/GatlingOssPluginSpec.scala
Motivation:
Wanted to publish a 3.6.0-M1 version for gatling (Java, Kotlin support). But as it isn't a stable version, the build plugin refused to deliver.
Modifications:
* Enhance the verification with possible milstone marker
Result:
Will be able to publish milestone version on sonatype
> feat: Milestones are publishable versions

- .github/workflows/build.yml
- .github/workflows/create_release.yml
- .github/workflows/release.yml
Motivation:
See olafurpg/setup-scala#49:
- olafurpg/setup-scala is no longer considered necessary by its maintainer and will probably be archived at some point.
- Ubuntu runners now include the official SBT launcher by default.
- actions/setup-java is the official action for setting up a JDK, so we might as well use that if it"s sufficient for our purpose.
Modifications:
- Replace olafurpg/setup-scala with actions/setup-java.
- Use Zulu JDK.
> chore: Switch GitHub actions from setup-scala to setup-java

- .github/workflows/create_release.yml
- src/main/scala/io/gatling/build/versioning/GatlingBump.scala
- src/main/scala/io/gatling/build/versioning/GatlingVersion.scala
- src/main/scala/io/gatling/build/versioning/GatlingVersioningPlugin.scala
- src/test/scala/io/gatling/build/versioning/FixedClock.scala
- src/test/scala/io/gatling/build/versioning/GatlingBumpSpec.scala
- src/test/scala/io/gatling/build/versioning/GatlingVersionSpec.scala
Motivation:
It's confusing when milestone is set on the current published version.
Modifications:
* Deprecated milestone bump method
* Add a milestone bump method for patch, minor and calver
Result:
Qualifier precedes stable version
> feat: order qualified version before stable version, MISC-327

- .github/workflows/build.yml
- build.sbt
- src/main/scala/io/gatling/build/automated/GatlingAutomatedScalafixPlugin.scala
- src/main/scala/io/gatling/build/automated/GatlingAutomatedScalafmtPlugin.scala
- src/main/scala/io/gatling/build/config/GatlingBuildConfigPlugin.scala
- src/sbt-test/scalafix/automated/test
Motivation:
During Scala steward test about using automatic migrations, we (@tpetillot and I)
found that scala-steward expected to be able to launch scalafixAll task but
during the CI for scala fix, our own task was not called, so the config file was
not written.
Modifications:
* move task declarations inside sbt graph (better usage of sbt)
* make scalafix and scalafixAll input task dependent on our task to copy configuration
* [BREAKING CHANGE] remove gatlingScalafixCheck custom task
Result:
Better usage of sbt and more broad support over our different tools
> fix: scalafix input task should depends on writing the configuration file

- src/main/resources/Apache2.license
- src/main/scala/io/gatling/build/GatlingOssPlugin.scala
- src/main/scala/io/gatling/build/license/Apache2LicenseFilePlugin.scala
Motivation:
This file ensure that end user will know the License applied to our open source libraries.
Modifications:
* Create a Apache2LicenseFilePlugin auto plugin
Result:
When project use our GatlingOssPlugin, it will automatically add this `LICENSE` file in `META-INF` directory inside the generated jar.
> feat: package Apache2 license in the generated jar, MISC-419

- build.sbt
- src/main/scala/io/gatling/build/compile/GatlingCompilerSettingsPlugin.scala
Motivation:
-target for jvm is deprecated
Modifications:
* replace -target by -release compiler options
Result:
Up to date with scalac
> feat: replace -target by -release compiler options

- build.sbt
- project/plugins.sbt
Motivation:
as this is a project that is itself its own plugin and that export as a plugin, we need to duplicate between build.sbt and project/plugins.sbt
Modifications:
* use same values for both sides
Result:
Aligned in auto-application and to external application
> fix: align plugins version to export

- build.sbt
- project/plugins.sbt
- src/main/scala/io/gatling/build/versioning/GatlingVersioningPlugin.scala
Motivations:
sbt-git is not maintained anymore. And there is a CVE on JGit that is triggered during a release.
Modifications:
* delete sbt-git dependencies
* add sbt-dynver
* remove custom parsing
Result:
Work identically:
* sbt show version is based on the last tag
* sbt -Dproject.version="1.2.3" "show version" doesn't work anymore but version can be overridden by sbt 'set version := "1.2.3"' "show version"
* gatlingBumpVersion and gatlingWriteBumpVersion still work
> feat: replace sbt-git by sbt-dynver

- build.sbt
- project/plugins.sbt
- project/project/PluginDependencies.scala
Motivation:
Threads scan show infected dependencies.
Our direct dependencies don't have newer version (for now)
Modifications:
* override dependency both in plugins.sbt and build.sbt (as this project is its own plugin)
Result:
Should still work (mostly compatible version)
Should avoid threats
> chore: overrides dependencies

- src/main/scala/io/gatling/build/GatlingCorpPlugin.scala
- src/main/scala/io/gatling/build/GatlingEnterpriseComponentPlugin.scala
- src/main/scala/io/gatling/build/GatlingOssPlugin.scala
- src/main/scala/io/gatling/build/basic/GatlingCompileAllPlugin.scala
Motivation:
We define this helper in different projects
Modifications:
* Add a plugin to declare this
Result:
The developer can now launch `sbt compileAll` or better `sbt ~compileAll` in order to compile all configurations for all projects (if root is the aggregated projects)
> feat: add compileAll task, MISC-483

- src/main/resources/default.scalafix.conf
- src/main/scala/io/gatling/build/GatlingOssPlugin.scala
- src/main/scala/io/gatling/build/automated/GatlingAutomatedScalafixPlugin.scala
- src/main/scala/io/gatling/build/sonatype/GatlingSonatypePlugin.scala
- src/sbt-test/gatling-build-plugin/loadPlugin/build.sbt
- src/sbt-test/gatling-build-plugin/loadPlugin/project/build.properties
- src/sbt-test/gatling-build-plugin/scalaVersion/project/build.properties
- src/sbt-test/scalafix/automated/build.sbt
- src/sbt-test/scalafix/automated/project/build.properties
- src/sbt-test/scalafix/none/build.sbt
- src/sbt-test/scalafix/none/project/build.properties
- src/sbt-test/scalafmt/automated/build.sbt
- src/sbt-test/scalafmt/automated/project/build.properties
- src/sbt-test/scalafmt/none/build.sbt
- src/sbt-test/scalafmt/none/project/build.properties
Motivation:
NeQuissimus/sort-imports is no longer maintained. Even though it works very well, scalafix complains about it being compiled against scalafix 0.9 and pollutes the logs.
Modifications:
* Configure the "new" OrganizeImports built-in rule to be as close as possible from current code
Result:
Small changes in code but use an uptodate version of scalafix rule
> feat: use OrganizeImports scalafix built-in rule, MISC-485

- src/main/scala/io/gatling/build/sonatype/GatlingSonatypePlugin.scala
Motivation:
Multi project (gatling) does not work
Modifications:
* remove publishSkip condition
Result:
Always try to publish the bundle
> fix: always publish bundle from root

- src/main/scala/io/gatling/build/sonatype/GatlingSonatypePlugin.scala
Motivation:
We don't check anything lately before manually clicking on publish on Sonatype website
Modification:
Directly ask for publication through the API
Result:
Less time to wait (no manual click)
> feat: fully release instead of only upload to sonatype
